# Generated by Django 5.0.1 on 2024-01-18 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundsEstate',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('sector', models.CharField(choices=[('bancos', 'Agências de Bancos'), ('educacional', 'Educação'), ('fiagro', 'Fiagro'), ('fundo_desenvolvimento', 'Fundo de Desenvolvimento'), ('hospitalar', 'Hospitalar'), ('hotel', 'Hotéis'), ('imoveis_logistica', 'Imóveis de Logística, Comercial ou Industrial'), ('imoveis_residenciais', 'Imóveis Residenciais'), ('lajes_corporativas', 'Lajes Corporativas'), ('shopping', 'Shopping'), ('papeis', 'Papéis'), ('varejo', 'Varejo'), ('outros', 'Outros')], max_length=50)),
                ('dividend_yield_avg_12m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacancy_financial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacancy_physical', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_assets', models.IntegerField(default=0)),
            ],
        ),
    ]
